skip_local_validator = true

[toolchain]

[features]
resolution = true
skip-lint = false

[programs.localnet]
anchor_core_staking = "28CvKn5HiiJ1i5SM3rX3cPTbp1QAwaHSFp4VRg4AhwGQ"

[provider]
cluster = "localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "cargo test"

[hooks]
