skip_local_validator = true

[toolchain]

[features]
resolution = true
skip-lint = false

[programs.localnet]
token22_ct = "3kjBCVZPCqW6e6JLFCBkTWPocDH1TD6GgB6XEiLw1qVc"

[provider]
cluster = "localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "cargo test"

[hooks]